### Classification Model for our dataset

In [1]:
import pandas as pd
import numpy as np
from configs.system import project_dir

In [2]:
p_dir = project_dir()
data_dir = p_dir.FEATURED_DIR

dataset_path = data_dir/'featured_dataset.csv'

In [3]:
df = pd.read_csv(dataset_path,index_col=0)

df.sample(2)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,...,Duration,Demand,StartMonth,StartWeek,EndMonth,EndWeek,DemandPerMonth,StartDayOfWeek,DemandPerDay,Shift
910,0,3,1,company,0,2022-03-18,19:36:52,2022-03-19,02:42:39,2022-03-18 19:36:00,...,426,18.59,3,4,3,5,103896.05,Friday,17.31,Night
32751,0,263,1,hotel,0,2021-11-28,11:44:19,2021-11-28,14:57:00,2021-11-28 11:44:00,...,193,22.30,11,6,11,6,71741.55,Sunday,17.81,Day

In [7]:
df['Target_Demand'] = (df['Demand']>df['Demand'].median()).astype(int)

In [5]:
df.sample(3)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,...,Demand,StartMonth,StartWeek,EndMonth,EndWeek,DemandPerMonth,StartDayOfWeek,DemandPerDay,Shift,Target_Demand
21411,108,139,1,public area,0,2022-01-23,14:27:14,2022-01-23,18:11:44,2022-01-23 14:27:00,...,13.10,1,6,1,6,109639.33,Sunday,17.81,Night,0
43838,0,430,1,camping,0,2022-08-13,20:28:59,2022-08-13,23:52:13,2022-08-13 20:28:00,...,19.41,8,5,8,5,143041.27,Saturday,17.41,Night,1
5317,0,22,1,hotel,0,2022-09-24,18:39:11,2022-09-24,22:13:48,2022-09-24 18:39:00,...,23.20,9,5,9,5,111771.80,Saturday,17.41,Night,1

In [6]:
df.columns

Index(['UserID', 'ChargerID', 'ChargerCompany', 'Location', 'ChargerType',
       'StartDay', 'StartTime', 'EndDay', 'EndTime', 'StartDatetime',
       'EndDatetime', 'Duration', 'Demand', 'StartMonth', 'StartWeek',
       'EndMonth', 'EndWeek', 'DemandPerMonth', 'StartDayOfWeek',
       'DemandPerDay', 'Shift', 'Target_Demand'],
      dtype='str')

In [4]:
categorical_columns = ['Shift','Location']
numerical_columns = ['ChargerCompany','ChargerType','Duration']
ordinal_columns = ['StartDayOfWeek']

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder

preprocessor = ColumnTransformer([
    ('cat',OneHotEncoder(),categorical_columns),
    ('num',StandardScaler(),numerical_columns),
    ('ord',OrdinalEncoder(),ordinal_columns)
])

In [9]:
X = df[['Shift','Location','ChargerCompany','ChargerType','Duration','StartDayOfWeek']]
y = df['Target_Demand']

In [10]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [11]:
X_train_prep = preprocessor.fit_transform(X_train)
X_test_prep = preprocessor.transform(X_test)

### Decision Tree Classifier

In [19]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

depths = [4,5,6,7,8,9,10,13,15,20]

dt_r = []

for depth in depths:
    dt = DecisionTreeClassifier(max_depth=depth,random_state=42)

    dt.fit(X_train_prep,y_train)

    y_pred = dt.predict(X_test_prep)

    y_pred_train = dt.predict(X_train_prep)

    accuracy_test = accuracy_score(y_pred,y_test)

    accuracy_train = accuracy_score(y_pred_train,y_train)

    dt_r.append({
        'depth' : depth,
        'test' : accuracy_test,
        'train' : accuracy_train
    })

In [13]:
dt_r

[{'depth': 4, 'test': 0.8885074831800083, 'train': 0.8861483007209063},
 {'depth': 5, 'test': 0.8891253604283949, 'train': 0.8884998283556471},
 {'depth': 6, 'test': 0.8911162982287519, 'train': 0.8912289735667697},
 {'depth': 7, 'test': 0.8922147466703282, 'train': 0.8924476484723652},
 {'depth': 8, 'test': 0.891528216394343, 'train': 0.8937693099897014},
 {'depth': 9, 'test': 0.8909103391459563, 'train': 0.8963439752832132},
 {'depth': 10, 'test': 0.8909103391459563, 'train': 0.8997596979059389},
 {'depth': 13, 'test': 0.8826033228065358, 'train': 0.9125472021970478},
 {'depth': 15, 'test': 0.8775229987642456, 'train': 0.9217473395125301},
 {'depth': 20, 'test': 0.8644102704929287, 'train': 0.9412118091314796}]

In [14]:
splits = [5,10,15,20,25,30]

dt_r = []

for split in splits:
    dt = DecisionTreeClassifier(min_samples_split = split,random_state=42)

    dt.fit(X_train_prep,y_train)

    y_pred = dt.predict(X_test_prep)

    y_pred_train = dt.predict(X_train_prep)

    accuracy_test = accuracy_score(y_test,y_pred)

    accuracy_train = accuracy_score(y_train,y_pred_train)

    dt_r.append({
        'split' : split,
        'test' : accuracy_test,
        'train' : accuracy_train
    })

In [15]:
dt_r

[{'split': 5, 'test': 0.8622133736097762, 'train': 0.9335049776862341},
 {'split': 10, 'test': 0.8701771248112041, 'train': 0.9217473395125301},
 {'split': 15, 'test': 0.8762872442674722, 'train': 0.9155853072433917},
 {'split': 20, 'test': 0.8806810380337773, 'train': 0.9112083762444215},
 {'split': 25, 'test': 0.8828092818893313, 'train': 0.9083247511156883},
 {'split': 30, 'test': 0.8849375257448854, 'train': 0.9062135255750086}]

In [16]:
from sklearn.metrics import f1_score, classification_report,roc_auc_score, precision_score, recall_score

In [17]:
dt = DecisionTreeClassifier(max_depth=10,min_samples_split=20,random_state=42)

dt.fit(X_train_prep,y_train)

y_pred = dt.predict(X_test_prep)

y_pred_prob = dt.predict_proba(X_test_prep)[:,1]

In [18]:
f1_s = f1_score(y_test,y_pred)
# f1_train = f1_score(y_train,y_pred_train)

roc_test = roc_auc_score(y_test,y_pred_prob)
accuracy = accuracy_score(y_test,y_pred)
precision_dt = precision_score(y_test,y_pred)
recall_dt = recall_score(y_test,y_pred)

report_dt = classification_report(y_test,y_pred)

results = []
results.append({
    'model' : 'Decision Tree',
    'Accuracy' : accuracy,
    'ROC' : roc_test,
    'F1' : f1_s,
    'Precision' : precision_dt,
    'Recall' : recall_dt
})

# print(results)
print(report_dt)

results

              precision    recall  f1-score   support

           0       0.91      0.87      0.89      7280
           1       0.88      0.91      0.89      7286

    accuracy                           0.89     14566
   macro avg       0.89      0.89      0.89     14566
weighted avg       0.89      0.89      0.89     14566

[{'model': 'Decision Tree',
  'Accuracy': 0.8913222573115475,
  'ROC': 0.9491974108104357,
  'F1': 0.8933360285695034,
  'Precision': 0.8774321641297155,
  'Recall': 0.9098270656052704}]

## Random forest Classifier

In [14]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
depths = [4,5,6,7,8,9,10,11,13,15]

rf_r = []

for depth in depths:
    rf = RandomForestClassifier(max_depth=depth,random_state=42,n_jobs=-1)
    rf.fit(X_train_prep,y_train)

    y_pred = rf.predict(X_test_prep)

    y_pred_train = rf.predict(X_train_prep)

    report = classification_report(y_test,y_pred)

    # print(report)

    accuracy = accuracy_score(y_test,y_pred)
    accuracy_train = accuracy_score(y_train,y_pred_train)

    rf_r.append({
        'depth' : depth,
        'accuracy_test' : accuracy,
        'train' : accuracy_train
    })

In [21]:
rf_r

[{'depth': 4,
  'accuracy_test': 0.8777976108746396,
  'train': 0.8737212495708891},
 {'depth': 5, 'accuracy_test': 0.881573527392558, 'train': 0.8778922073463783},
 {'depth': 6, 'accuracy_test': 0.881710833447755, 'train': 0.879351184346035},
 {'depth': 7,
  'accuracy_test': 0.8891253604283949,
  'train': 0.8898729831788534},
 {'depth': 8,
  'accuracy_test': 0.8907730330907593,
  'train': 0.8927909371781668},
 {'depth': 9,
  'accuracy_test': 0.8924893587807222,
  'train': 0.8947476828012358},
 {'depth': 10,
  'accuracy_test': 0.8937937663050941,
  'train': 0.8983693786474425},
 {'depth': 11,
  'accuracy_test': 0.8950981738294659,
  'train': 0.9017164435290079},
 {'depth': 13,
  'accuracy_test': 0.8957160510778526,
  'train': 0.9090971507037419},
 {'depth': 15,
  'accuracy_test': 0.8937937663050941,
  'train': 0.9193614830072091}]

In [22]:
estimators = [100,200,350,500]

rf_r = []

for n in estimators:
    rf = RandomForestClassifier(n_estimators=n,n_jobs=-1,random_state=42)

    rf.fit(X_train_prep,y_train)

    y_pred = rf.predict(X_test_prep)

    y_pred_train = rf.predict(X_train_prep)

    report = classification_report(y_test,y_pred)

    # print(report)

    accuracy = accuracy_score(y_test,y_pred)
    accuracy_train = accuracy_score(y_train,y_pred_train)

    rf_r.append({
        'estimators' : n,
        'accuracy_test' : accuracy,
        'train' : accuracy_train
    })

In [23]:
rf_r

[{'estimators': 100,
  'accuracy_test': 0.873747082246327,
  'train': 0.9476656368005493},
 {'estimators': 200,
  'accuracy_test': 0.8748455306879034,
  'train': 0.9476828012358394},
 {'estimators': 350,
  'accuracy_test': 0.8745709185775092,
  'train': 0.9476828012358394},
 {'estimators': 500,
  'accuracy_test': 0.8743649594947137,
  'train': 0.9476828012358394}]

In [24]:
splits = [5,10,15,18,20,25]

rf_r = []

for split in splits:
    rf = RandomForestClassifier(n_estimators=100,min_samples_split=split,n_jobs=-1,random_state=42)


    rf.fit(X_train_prep,y_train)
    
    y_pred = rf.predict(X_test_prep)

    y_pred_train = rf.predict(X_train_prep)

    report = classification_report(y_test,y_pred)

    accuracy = accuracy_score(y_test,y_pred)
    accuracy_train = accuracy_score(y_train,y_pred_train)

    rf_r.append({
            'split' : split,
            'accuracy_test' : accuracy,
            'train' : accuracy_train
        })

In [25]:
rf_r

[{'split': 5,
  'accuracy_test': 0.8797885486749966,
  'train': 0.9355303810504635},
 {'split': 10,
  'accuracy_test': 0.8871344226280379,
  'train': 0.9215756951596292},
 {'split': 15,
  'accuracy_test': 0.8904297679527667,
  'train': 0.9144524545142465},
 {'split': 18,
  'accuracy_test': 0.8921460936427297,
  'train': 0.9113628561620323},
 {'split': 20,
  'accuracy_test': 0.891940134559934,
  'train': 0.9099038791623756},
 {'split': 25,
  'accuracy_test': 0.8924893587807222,
  'train': 0.9063508410573292}]

In [21]:
rf = RandomForestClassifier(n_estimators=100,n_jobs=-1,random_state=42,min_samples_split=20,max_depth=13)

rf.fit(X_train_prep,y_train)

y_pred = rf.predict(X_test_prep)
y_pred_prob = rf.predict_proba(X_test_prep)[:,1]

accuracy_s = accuracy_score(y_test,y_pred)

roc_auc_s = roc_auc_score(y_test,y_pred_prob)

f1_s = f1_score(y_test,y_pred)

precision_rf = precision_score(y_test,y_pred)
recall_rf = recall_score(y_test,y_pred)

In [27]:
results

[{'model': 'Decision Tree',
  'Accuracy': 0.8913222573115475,
  'ROC': 0.9491974108104357,
  'F1': 0.8933360285695034,
  'Precision': 0.8774321641297155,
  'Recall': 0.9098270656052704},
 {'model': 'RandomForestClassifier',
  'Accuracy': 0.8964025813538377,
  'ROC': 0.9558462733738948,
  'F1': 0.900270966889168,
  'Precision': 0.8681963033779477,
  'Recall': 0.9348064781773264}]

In [28]:
from sklearn.linear_model import LogisticRegression

cs =[0.01,0.1,1,10]
rf_r = []
for c in cs:
    lg = LogisticRegression(C=c,random_state=42)

    lg.fit(X_train_prep,y_train)
        
    y_pred = lg.predict(X_test_prep)

    y_pred_train = lg.predict(X_train_prep)

    report = classification_report(y_test,y_pred)

    accuracy = accuracy_score(y_test,y_pred)
    accuracy_train = accuracy_score(y_train,y_pred_train)

    rf_r.append({
            'c' : c,
            'accuracy_test' : accuracy,
            'train' : accuracy_train
        })

In [29]:
rf_r

[{'c': 0.01, 'accuracy_test': 0.8379788548674997, 'train': 0.8401819430140748},
 {'c': 0.1, 'accuracy_test': 0.8403130578058492, 'train': 0.8416237555784415},
 {'c': 1, 'accuracy_test': 0.8407249759714404, 'train': 0.841743906625472},
 {'c': 10, 'accuracy_test': 0.8407936289990389, 'train': 0.8416752488843117}]

In [30]:
max_iters = [50,100,150,200]

rf_r = []
for iter in max_iters:
    lg = LogisticRegression(max_iter=iter,random_state=42)
    
    lg.fit(X_train_prep,y_train)
            
    y_pred = lg.predict(X_test_prep)

    y_pred_train = lg.predict(X_train_prep)

    report = classification_report(y_test,y_pred)

    accuracy = accuracy_score(y_test,y_pred)
    accuracy_train = accuracy_score(y_train,y_pred_train)

    rf_r.append({
            'iter' : iter,
            'accuracy_test' : accuracy,
            'train' : accuracy_train
        })

In [31]:
rf_r

[{'iter': 50, 'accuracy_test': 0.8407249759714404, 'train': 0.841743906625472},
 {'iter': 100,
  'accuracy_test': 0.8407249759714404,
  'train': 0.841743906625472},
 {'iter': 150,
  'accuracy_test': 0.8407249759714404,
  'train': 0.841743906625472},
 {'iter': 200,
  'accuracy_test': 0.8407249759714404,
  'train': 0.841743906625472}]

In [32]:
lg = LogisticRegression(max_iter=100,C=0.1,random_state=42)

lg.fit(X_train_prep,y_train)

y_pred = lg.predict(X_test_prep)
y_pred_prob = lg.predict_proba(X_test_prep)[:,1]

accuracy_s = accuracy_score(y_test,y_pred)

roc_auc_s = roc_auc_score(y_test,y_pred_prob)

f1_s = f1_score(y_test,y_pred)
precision_lg = precision_score(y_test,y_pred)
recall_lg = recall_score(y_test,y_pred)


results.append({
    'model' : 'LogisticRegression',
    'Accuracy' : accuracy_s,
    'ROC' : roc_auc_s,
    'F1': f1_s,
    'Precision' : precision_lg,
    'Recall' : recall_lg
})

In [33]:
results

[{'model': 'Decision Tree',
  'Accuracy': 0.8913222573115475,
  'ROC': 0.9491974108104357,
  'F1': 0.8933360285695034,
  'Precision': 0.8774321641297155,
  'Recall': 0.9098270656052704},
 {'model': 'RandomForestClassifier',
  'Accuracy': 0.8964025813538377,
  'ROC': 0.9558462733738948,
  'F1': 0.900270966889168,
  'Precision': 0.8681963033779477,
  'Recall': 0.9348064781773264},
 {'model': 'LogisticRegression',
  'Accuracy': 0.8403130578058492,
  'ROC': 0.912548857435455,
  'F1': 0.8441227717464147,
  'Precision': 0.8247773703509691,
  'Recall': 0.8643974746088389}]

## XG Classifier

In [34]:
from xgboost import XGBClassifier

rates = [0.01,0.1,0.3,1.0]

rf_r = []

for rate in rates:
    xg = XGBClassifier(learning_rate=rate,random_state=42,n_jobs=-1)


    xg.fit(X_train_prep,y_train)
                
    y_pred = xg.predict(X_test_prep)

    y_pred_train = xg.predict(X_train_prep)

    # report = classification_report(y_test,y_pred)

    accuracy = accuracy_score(y_test,y_pred)
    accuracy_train = accuracy_score(y_train,y_pred_train)

    rf_r.append({
            'rate' : rate,
            'accuracy_test' : accuracy,
            'train' : accuracy_train
        })

In [35]:
rf_r

[{'rate': 0.01,
  'accuracy_test': 0.8931758890567074,
  'train': 0.8920700308959835},
 {'rate': 0.1,
  'accuracy_test': 0.8948922147466704,
  'train': 0.8966357706831445},
 {'rate': 0.3,
  'accuracy_test': 0.8947549086914733,
  'train': 0.9025231719876416},
 {'rate': 1.0,
  'accuracy_test': 0.8874090347384319,
  'train': 0.9131651218674905}]

In [36]:
depths = [4,5,6,7,8,9,10,12,13,15]

rf_r = []

for depth in depths:
    xg = XGBClassifier(learning_rate=0.1,random_state=42,n_jobs=-1,max_depth=depth)


    xg.fit(X_train_prep,y_train)
                
    y_pred = xg.predict(X_test_prep)

    y_pred_train = xg.predict(X_train_prep)
    accuracy = accuracy_score(y_test,y_pred)
    accuracy_train = accuracy_score(y_train,y_pred_train)

    rf_r.append({
            'depth' : depth,
            'accuracy_test' : accuracy,
            'train' : accuracy_train
        })

In [37]:
rf_r

[{'depth': 4, 'accuracy_test': 0.891802828504737, 'train': 0.8905252317198764},
 {'depth': 5, 'accuracy_test': 0.8938624193326926, 'train': 0.893254376930999},
 {'depth': 6,
  'accuracy_test': 0.8948922147466704,
  'train': 0.8966357706831445},
 {'depth': 7,
  'accuracy_test': 0.8955100919950569,
  'train': 0.8987298317885342},
 {'depth': 8,
  'accuracy_test': 0.8948922147466704,
  'train': 0.9022828698935805},
 {'depth': 9,
  'accuracy_test': 0.8945489496086777,
  'train': 0.9047545485753519},
 {'depth': 10,
  'accuracy_test': 0.8932445420843059,
  'train': 0.9087710264332304},
 {'depth': 12,
  'accuracy_test': 0.8907730330907593,
  'train': 0.9163062135255751},
 {'depth': 13,
  'accuracy_test': 0.889262666483592,
  'train': 0.9196704428424305},
 {'depth': 15,
  'accuracy_test': 0.8850748318000824,
  'train': 0.9252488843117062}]

In [38]:
estimators = [100,150,200,250]

rf_r = []

for n in estimators:
    xg = XGBClassifier(learning_rate=0.1,random_state=42,n_jobs=-1,max_depth=7,n_estimators=n)


    xg.fit(X_train_prep,y_train)
                
    y_pred = xg.predict(X_test_prep)

    y_pred_train = xg.predict(X_train_prep)
    accuracy = accuracy_score(y_test,y_pred)
    accuracy_train = accuracy_score(y_train,y_pred_train)

    rf_r.append({
            'estimators' : n,
            'accuracy_test' : accuracy,
            'train' : accuracy_train
        })

In [39]:
rf_r

[{'estimators': 100,
  'accuracy_test': 0.8955100919950569,
  'train': 0.8987298317885342},
 {'estimators': 150,
  'accuracy_test': 0.8955100919950569,
  'train': 0.9008410573292138},
 {'estimators': 200,
  'accuracy_test': 0.8949608677742689,
  'train': 0.9024545142464813},
 {'estimators': 250,
  'accuracy_test': 0.8939997253878896,
  'train': 0.9040508067284586}]

In [40]:
### XG boost classifier

xg = XGBClassifier(max_depth=7,learning_rate=0.1,n_estimators=100,subsample=0.80,colsample_bytree=0.80,random_state=42,n_jobs=-1)

xg.fit(X_train_prep,y_train)

y_pred = xg.predict(X_test_prep)
y_pred_prob = xg.predict_proba(X_test_prep)[:,1]

accuracy = accuracy_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)
precision_xg = precision_score(y_test,y_pred)
recall_xg = recall_score(y_test,y_pred)


roc = roc_auc_score(y_test,y_pred_prob)


results.append({
    'model' : 'XGBClassifier',
    'Accuracy' : accuracy,
    'ROC' : roc,
    'F1' : f1,
    'Precision' : precision_xg,
    'Recall' : recall_xg
})

In [41]:
results

[{'model': 'Decision Tree',
  'Accuracy': 0.8913222573115475,
  'ROC': 0.9491974108104357,
  'F1': 0.8933360285695034,
  'Precision': 0.8774321641297155,
  'Recall': 0.9098270656052704},
 {'model': 'RandomForestClassifier',
  'Accuracy': 0.8964025813538377,
  'ROC': 0.9558462733738948,
  'F1': 0.900270966889168,
  'Precision': 0.8681963033779477,
  'Recall': 0.9348064781773264},
 {'model': 'LogisticRegression',
  'Accuracy': 0.8403130578058492,
  'ROC': 0.912548857435455,
  'F1': 0.8441227717464147,
  'Precision': 0.8247773703509691,
  'Recall': 0.8643974746088389},
 {'model': 'XGBClassifier',
  'Accuracy': 0.8950981738294659,
  'ROC': 0.9573986257703317,
  'F1': 0.8985122210414452,
  'Precision': 0.8705276705276705,
  'Recall': 0.9283557507548723}]

### Gradient Boosting

In [42]:
from sklearn.ensemble import GradientBoostingClassifier

In [43]:


rates = [0.01,0.1,0.3,1.0]

rf_r = []

for rate in rates:
    gb = GradientBoostingClassifier(learning_rate=rate,random_state=42)
    gb.fit(X_train_prep,y_train)
                
    y_pred = gb.predict(X_test_prep)

    y_pred_train = gb.predict(X_train_prep)


    accuracy = accuracy_score(y_test,y_pred)

    accuracy_train = accuracy_score(y_train,y_pred_train)

    rf_r.append({
            'rate' : rate,
            'accuracy_test' : accuracy,
            'train' : accuracy_train
        })

In [44]:
rf_r

[{'rate': 0.01,
  'accuracy_test': 0.8839763833585061,
  'train': 0.8832303467215928},
 {'rate': 0.1,
  'accuracy_test': 0.8909789921735548,
  'train': 0.8890319258496395},
 {'rate': 0.3,
  'accuracy_test': 0.893656460249897,
  'train': 0.8934088568486097},
 {'rate': 1.0,
  'accuracy_test': 0.8906357270355623,
  'train': 0.8925163062135256}]

In [45]:
estimators = [100,150,200,250]

rf_r = []

for n in estimators:
    gb = GradientBoostingClassifier(learning_rate=0.1,random_state=42,n_estimators=n)


    gb.fit(X_train_prep,y_train)
                
    y_pred = gb.predict(X_test_prep)

    y_pred_train = gb.predict(X_train_prep)
    accuracy = accuracy_score(y_test,y_pred)
    accuracy_train = accuracy_score(y_train,y_pred_train)

    rf_r.append({
            'estimators' : n,
            'accuracy_test' : accuracy,
            'train' : accuracy_train
        })

In [46]:
rf_r

[{'estimators': 100,
  'accuracy_test': 0.8909789921735548,
  'train': 0.8890319258496395},
 {'estimators': 150,
  'accuracy_test': 0.891802828504737,
  'train': 0.8900102986611741},
 {'estimators': 200,
  'accuracy_test': 0.8927639708911163,
  'train': 0.8917782354960522},
 {'estimators': 250,
  'accuracy_test': 0.8933131951119044,
  'train': 0.8925677995193958}]

In [47]:
depths = [4,5,6,7,8,9,10,12,13,15]

rf_r = []

for depth in depths:
    gb = GradientBoostingClassifier(learning_rate=0.1,random_state=42,max_depth=depth,n_estimators=150)


    gb.fit(X_train_prep,y_train)
                
    y_pred = gb.predict(X_test_prep)

    y_pred_train = gb.predict(X_train_prep)
    accuracy = accuracy_score(y_test,y_pred)
    accuracy_train = accuracy_score(y_train,y_pred_train)

    rf_r.append({
            'depth' : depth,
            'accuracy_test' : accuracy,
            'train' : accuracy_train
        })

In [48]:
rf_r

[{'depth': 4,
  'accuracy_test': 0.8924207057531237,
  'train': 0.8927737727428767},
 {'depth': 5,
  'accuracy_test': 0.8943429905258822,
  'train': 0.8973395125300377},
 {'depth': 6,
  'accuracy_test': 0.8941370314430866,
  'train': 0.9023000343288706},
 {'depth': 7,
  'accuracy_test': 0.8927639708911163,
  'train': 0.9084963954685891},
 {'depth': 8, 'accuracy_test': 0.89166552244954, 'train': 0.9145382766906969},
 {'depth': 9,
  'accuracy_test': 0.8899491967595771,
  'train': 0.9246481290765534},
 {'depth': 10,
  'accuracy_test': 0.887546340793629,
  'train': 0.9318400274630965},
 {'depth': 12,
  'accuracy_test': 0.8797885486749966,
  'train': 0.9451767936834878},
 {'depth': 13,
  'accuracy_test': 0.8770424275710559,
  'train': 0.9474424991417782},
 {'depth': 15,
  'accuracy_test': 0.8755320609638885,
  'train': 0.9476828012358394}]

In [49]:

gb = GradientBoostingClassifier(max_depth=6,learning_rate=0.3,n_estimators=150,subsample=0.80,random_state=42)

gb.fit(X_train_prep,y_train)

y_pred = gb.predict(X_test_prep)
y_pred_prob = gb.predict_proba(X_test_prep)[:,1]

accuracy = accuracy_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)

roc = roc_auc_score(y_test,y_pred_prob)
precision_gb = precision_score(y_test,y_pred)
recall_gb = recall_score(y_test,y_pred)


results.append({
    'model' : 'gradient Boosting',
    'Accuracy' : accuracy,
    'ROC' : roc,
    'F1' : f1,
    'Precision' : precision_gb,
    'Recall' : recall_gb
})

In [50]:
results

[{'model': 'Decision Tree',
  'Accuracy': 0.8913222573115475,
  'ROC': 0.9491974108104357,
  'F1': 0.8933360285695034,
  'Precision': 0.8774321641297155,
  'Recall': 0.9098270656052704},
 {'model': 'RandomForestClassifier',
  'Accuracy': 0.8964025813538377,
  'ROC': 0.9558462733738948,
  'F1': 0.900270966889168,
  'Precision': 0.8681963033779477,
  'Recall': 0.9348064781773264},
 {'model': 'LogisticRegression',
  'Accuracy': 0.8403130578058492,
  'ROC': 0.912548857435455,
  'F1': 0.8441227717464147,
  'Precision': 0.8247773703509691,
  'Recall': 0.8643974746088389},
 {'model': 'XGBClassifier',
  'Accuracy': 0.8950981738294659,
  'ROC': 0.9573986257703317,
  'F1': 0.8985122210414452,
  'Precision': 0.8705276705276705,
  'Recall': 0.9283557507548723},
 {'model': 'gradient Boosting',
  'Accuracy': 0.8896059316215845,
  'ROC': 0.9522289190016682,
  'F1': 0.8927857047606348,
  'Precision': 0.8681275933609959,
  'Recall': 0.9188855339006313}]

## Light GBM classifier

In [51]:
from lightgbm import LGBMClassifier

In [52]:
leaves = [7,8,9,10,12,13,15,20,24,28]

rf_r = []

for leave in leaves:
    lgm = LGBMClassifier(learning_rate=0.1,random_state=42,num_leaves=leave,n_jobs=-1)


    lgm.fit(X_train_prep,y_train)
                
    y_pred = lgm.predict(X_test_prep)

    y_pred_train = lgm.predict(X_train_prep)
    accuracy = accuracy_score(y_test,y_pred)
    accuracy_train = accuracy_score(y_train,y_pred_train)

    rf_r.append({
            'leave' : leave,
            'accuracy_test' : accuracy,
            'train' : accuracy_train
        })

[LightGBM] [Info] Number of positive: 29095, number of negative: 29165
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.032064 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 298
[LightGBM] [Info] Number of data points in the train set: 58260, number of used features: 19
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499399 -> initscore=-0.002403
[LightGBM] [Info] Start training from score -0.002403
[LightGBM] [Info] Number of positive: 29095, number of negative: 29165
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.018496 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 298
[LightGBM] [Info] Number of data points in the train set: 58260, number of used features: 19
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499399 -> initscore=-0.002403
[LightGBM] [Info] Start training from score -0.002403
[LightGBM] [Info] Number of positive: 29095, number of negative: 29165
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.023500 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 298
[LightGBM] [Info] Number of data points in the train set: 58260, number of used features: 19
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499399 -> initscore=-0.002403
[LightGBM] [Info] Start training from score -0.002403
[LightGBM] [Info] Number of positive: 29095, number of negative: 29165
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000402 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 298
[LightGBM] [Info] Number of data points in the train set: 58260, number of used features: 19
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499399 -> initscore=-0.002403
[LightGBM] [Info] Start training from score -0.002403
[LightGBM] [Info] Number of positive: 29095, number of negative: 29165
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.024761 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 298
[LightGBM] [Info] Number of data points in the train set: 58260, number of used features: 19
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499399 -> initscore=-0.002403
[LightGBM] [Info] Start training from score -0.002403
[LightGBM] [Info] Number of positive: 29095, number of negative: 29165
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.020737 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 298
[LightGBM] [Info] Number of data points in the train set: 58260, number of used features: 19
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499399 -> initscore=-0.002403
[LightGBM] [Info] Start training from score -0.002403
[LightGBM] [Info] Number of positive: 29095, number of negative: 29165
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.023703 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 298
[LightGBM] [Info] Number of data points in the train set: 58260, number of used features: 19
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499399 -> initscore=-0.002403
[LightGBM] [Info] Start training from score -0.002403
[LightGBM] [Info] Number of positive: 29095, number of negative: 29165
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.020780 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 298
[LightGBM] [Info] Number of data points in the train set: 58260, number of used features: 19
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499399 -> initscore=-0.002403
[LightGBM] [Info] Start training from score -0.002403
[LightGBM] [Info] Number of positive: 29095, number of negative: 29165
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003226 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 298
[LightGBM] [Info] Number of data points in the train set: 58260, number of used features: 19
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499399 -> initscore=-0.002403
[LightGBM] [Info] Start training from score -0.002403
[LightGBM] [Info] Number of positive: 29095, number of negative: 29165
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000431 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 298
[LightGBM] [Info] Number of data points in the train set: 58260, number of used features: 19
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499399 -> initscore=-0.002403
[LightGBM] [Info] Start training from score -0.002403

In [53]:
rf_r

[{'leave': 7,
  'accuracy_test': 0.8914595633667445,
  'train': 0.8901132852729146},
 {'leave': 8, 'accuracy_test': 0.891253604283949, 'train': 0.8900789564023344},
 {'leave': 9,
  'accuracy_test': 0.8922147466703282,
  'train': 0.8903879162375558},
 {'leave': 10,
  'accuracy_test': 0.8932445420843059,
  'train': 0.8909028492962582},
 {'leave': 12,
  'accuracy_test': 0.8929012769463134,
  'train': 0.8916065911431514},
 {'leave': 13,
  'accuracy_test': 0.8924207057531237,
  'train': 0.8910744936491589},
 {'leave': 15,
  'accuracy_test': 0.8934505011671015,
  'train': 0.8918640576725025},
 {'leave': 20,
  'accuracy_test': 0.8947549086914733,
  'train': 0.8935976656368005},
 {'leave': 24,
  'accuracy_test': 0.8935878072222985,
  'train': 0.8939066254720219},
 {'leave': 28,
  'accuracy_test': 0.8950981738294659,
  'train': 0.8955887401304498}]

In [54]:
depths = [4,5,6,7,8,9,10,12,13,15]

rf_r = []

for depth in depths:
    lgm = LGBMClassifier(learning_rate=0.1,random_state=42,max_depth=depth,n_estimators=150)


    lgm.fit(X_train_prep,y_train)
                
    y_pred = lgm.predict(X_test_prep)

    y_pred_train = lgm.predict(X_train_prep)
    accuracy = accuracy_score(y_test,y_pred)
    accuracy_train = accuracy_score(y_train,y_pred_train)

    rf_r.append({
            'depth' : depth,
            'accuracy_test' : accuracy,
            'train' : accuracy_train
        })

[LightGBM] [Info] Number of positive: 29095, number of negative: 29165
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000712 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 298
[LightGBM] [Info] Number of data points in the train set: 58260, number of used features: 19
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499399 -> initscore=-0.002403
[LightGBM] [Info] Start training from score -0.002403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 29095, number of negative: 29165
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000647 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 298
[LightGBM] [Info] Number of data points in the train set: 58260, number of used features: 19
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499399 -> initscore=-0.002403
[LightGBM] [Info] Start training from score -0.002403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 29095, number of negative: 29165
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000596 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 298
[LightGBM] [Info] Number of data points in the train set: 58260, number of used features: 19
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499399 -> initscore=-0.002403
[LightGBM] [Info] Start training from score -0.002403
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 29095, number of negative: 29165
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000464 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 298
[LightGBM] [Info] Number of data points in the train set: 58260, number of used features: 19
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499399 -> initscore=-0.002403
[LightGBM] [Info] Start training from score -0.002403
[LightGBM] [Info] Number of positive: 29095, number of negative: 29165
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000668 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.

In [55]:
rf_r

[{'depth': 4,
  'accuracy_test': 0.8933131951119044,
  'train': 0.8932715413662891},
 {'depth': 5,
  'accuracy_test': 0.8951668268570644,
  'train': 0.8967044284243049},
 {'depth': 6,
  'accuracy_test': 0.8944802965810792,
  'train': 0.8974939924476485},
 {'depth': 7,
  'accuracy_test': 0.8937937663050941,
  'train': 0.8974939924476485},
 {'depth': 8,
  'accuracy_test': 0.8949608677742689,
  'train': 0.8980947476828013},
 {'depth': 9,
  'accuracy_test': 0.8941370314430866,
  'train': 0.8981634054239616},
 {'depth': 10,
  'accuracy_test': 0.8944116435534807,
  'train': 0.8976999656711294},
 {'depth': 12,
  'accuracy_test': 0.8950295208018674,
  'train': 0.8979574322004806},
 {'depth': 13,
  'accuracy_test': 0.8935878072222985,
  'train': 0.8977342945417096},
 {'depth': 15,
  'accuracy_test': 0.8946862556638748,
  'train': 0.8981634054239616}]

In [59]:

lgm = LGBMClassifier(max_depth=8,learning_rate=0.1,n_estimators=150,subsample=0.80,random_state=42,num_leaves=20)

lgm.fit(X_train_prep,y_train)

y_pred = lgm.predict(X_test_prep)
y_pred_prob = lgm.predict_proba(X_test_prep)[:,1]

accuracy = accuracy_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)

precision_lgm = precision_score(y_test,y_pred)
recall_lbm = recall_score(y_test,y_pred)
roc = roc_auc_score(y_test,y_pred_prob)


results.append({
    'model' : 'Light GMB',
    'Accuracy' : accuracy,
    'ROC' : roc,
    'F1' : f1,
    'Precision' : precision_lgm,
    'Recall' : recall_lbm
})

[LightGBM] [Info] Number of positive: 29095, number of negative: 29165
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001443 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 298
[LightGBM] [Info] Number of data points in the train set: 58260, number of used features: 19
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.499399 -> initscore=-0.002403
[LightGBM] [Info] Start training from score -0.002403

In [60]:
results

[{'model': 'Decision Tree',
  'Accuracy': 0.8913222573115475,
  'ROC': 0.9491974108104357,
  'F1': 0.8933360285695034,
  'Precision': 0.8774321641297155,
  'Recall': 0.9098270656052704},
 {'model': 'RandomForestClassifier',
  'Accuracy': 0.8964025813538377,
  'ROC': 0.9558462733738948,
  'F1': 0.900270966889168,
  'Precision': 0.8681963033779477,
  'Recall': 0.9348064781773264},
 {'model': 'LogisticRegression',
  'Accuracy': 0.8403130578058492,
  'ROC': 0.912548857435455,
  'F1': 0.8441227717464147,
  'Precision': 0.8247773703509691,
  'Recall': 0.8643974746088389},
 {'model': 'XGBClassifier',
  'Accuracy': 0.8950981738294659,
  'ROC': 0.9573986257703317,
  'F1': 0.8985122210414452,
  'Precision': 0.8705276705276705,
  'Recall': 0.9283557507548723},
 {'model': 'gradient Boosting',
  'Accuracy': 0.8896059316215845,
  'ROC': 0.9522289190016682,
  'F1': 0.8927857047606348,
  'Precision': 0.8681275933609959,
  'Recall': 0.9188855339006313},
 {'model': 'Light GMB',
  'Accuracy': 0.8944116435534807,
  'ROC': 0.9570828199044985,
  'F1': 0.8980106100795756},
 {'model': 'Light GMB',
  'Accuracy': 0.8944116435534807,
  'ROC': 0.9570828199044985,
  'F1': 0.8980106100795756,
  'Precision': 0.8687451886066204,
  'Recall': 0.9293164973922591}]

In [12]:
model_dir = p_dir.MODEL_DIR
model_dir

PosixPath('/home/arson/birdy/ds-project/ev-project/models')

In [22]:
import pickle

In [24]:


with open (model_dir/'classification_rf.pkl','wb') as file:
    pickle.dump(rf,file)

In [25]:
with open (model_dir/'classification_preprocessor.pkl','wb') as file:
    pickle.dump(preprocessor,file)